### ISSUE TITLE
support ethermint vesting account 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/rollapp-evm#169]
We can either port the vesting account impl from the evmos/ethermint repo or alternatively only allow a whitelist addresses/gov module to create vesting accounts. In that case we need a gov proposal to be able to change the whitelisted addresses allowed to create vesting account.

**Comment by omritoptix** [comment]
as agreed we're gonna whitelist usage for vesting. with that being said we need to modify 2 ante handlers:

- [ ] Whitelist direct vesting messages
- [ ] Disable authz.Exec vesting messages (as I believe this can currently by pass the whitelist mechanism)

**Comment by danwt** [comment]
related https://github.com/dymensionxyz/rollapp-evm/pull/216
