### ISSUE TITLE
proto gen doesn't work

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/rollapp-evm#171]
In [750d1e7](https://github.com/dymensionxyz/rollapp-evm/commit/750d1e70ad052daf7b2942bcecaf0dddfbc17d90)

```
make proto-gen 
Generating Protobuf files
BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.

Usage: dirname FILENAME

Strip non-directory suffix from FILENAME
make: *** [proto-gen] Error 123
```

**Comment by hoangdv2429** [comment]
we don't have any proto in current proto folder so it will fail... If you put proto files in proto folder it will work.  The script is not wrong though, except for these 2 lines https://github.com/dymensionxyz/rollapp-evm/blob/8d37db874902eb483293894333416d54bd051e72/scripts/protogen.sh#L30 and not handling cases where there isn't any proto files.
