### ISSUE TITLE
 evidence.MaxBytesEvidence is greater than upper bound, 1048576 > 500000

### ISSUE THREAD

**Issue by ThanhTuan1695** [dymensionxyz/rollapp-evm#238]
**Describe the bug**
i got the bug during following the readme from this repot. 

`Error: failed to read genesis doc from file: error reading GenesisDoc at /root/.rollapp_evm/config/genesis.json: evidence.MaxBytesEvidence is greater than upper bound, 1048576 > 500000`

**To Reproduce**
i ran through step by step from #installing--getting-started section
But when i tried to run `sh scripts/init.sh`
then i got the bug. 

`Error: failed to read genesis doc from file: error reading GenesisDoc at /root/.rollapp_evm/config/genesis.json: evidence.MaxBytesEvidence is greater than upper bound, 1048576 > 500000`

**Screenshots**
![image](https://github.com/dymensionxyz/rollapp-evm/assets/23187957/9a532851-6504-45b3-bf94-2d7eebfd2f3c)

**VPS (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**

**Comment by omritoptix** [comment]
fixed here: https://github.com/dymensionxyz/rollapp-evm/pull/240
